# Set prefix key to Ctrl-b
set-option -g prefix C-b

# Split panes using | and -
bind v split-window -h
bind s split-window -v
unbind '"'
unbind %

# Make pane resizing repeatable by holding down the key
# -r allows repeating the command by holding the key
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# enable mouse support
set -g mouse on

# enable focus events
set -g focus-events on

# enable vi mode in copy
setw -g mode-keys vi

# reload tmux.conf
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'schasse/tmux-jump'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-sidebar'


# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
