# GitHub Dark High Contrast palette -> @thm_* variables
set -g @thm_bg          "#0a0c10"
set -g @thm_bg_dim      "#010409"
set -g @thm_text        "#f0f3f6"

# neutrals
set -g @thm_surface_0   "#525964"
set -g @thm_surface_1   "#272b33"
set -g @thm_overlay_0   "#7a828e"
set -g @thm_overlay_1   "#9ea7b3"
set -g @thm_overlay_2   "#bdc4cc"

# accents
set -g @thm_red         "#ff9492"
set -g @thm_maroon      "#ffb1af"
set -g @thm_green       "#26cd4d"
set -g @thm_yellow      "#f0b72f"
set -g @thm_peach       "#f7c843"
set -g @thm_blue        "#71b7ff"
set -g @thm_sky         "#91cbff"
set -g @thm_sapphire    "#56d4dd"
set -g @thm_cyan        "#39c5cf"
set -g @thm_mauve       "#dbb7ff"  # purple-ish
set -g @thm_pink        "#cb9eff"
set -g @thm_rosewater   "#f0f3f6"  # use fg as "rose" for light contrast
