# GitHub Light High Contrast palette -> @thm_* variables
set -g @thm_bg          "#ffffff"
set -g @thm_bg_dim      "#e7ecf0"
set -g @thm_text        "#0e1116"

# neutrals
set -g @thm_surface_0   "#ced5dc"
set -g @thm_surface_1   "#e7ecf0"
set -g @thm_overlay_0   "#88929d"
set -g @thm_overlay_1   "#4b535d"
set -g @thm_overlay_2   "#0e1116"

# accents
set -g @thm_red         "#a0111f"
set -g @thm_maroon      "#86061d"
set -g @thm_green       "#055d20"
set -g @thm_yellow      "#744500"
set -g @thm_peach       "#956400"
set -g @thm_blue        "#0349b4"
set -g @thm_sky         "#1168e3"
set -g @thm_sapphire    "#368cf9"
set -g @thm_cyan        "#1b7c83"
set -g @thm_mauve       "#622cbc"
set -g @thm_pink        "#971368"
set -g @thm_rosewater   "#0e1116"
