#!/usr/bin/env zsh

FONT_FACE="Atkinson Hyperlegible Mono"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins-desktop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=32 \
    color=0xff2e3440 \
    margin=0 \
    sticky=on \
    padding_left=10 \
    padding_right=10 \
    notch_width=0 \
    display=main \

sketchybar --default \
    background.height=26 \
    background.color=0xff3b4252 \
    background.corner_radius=5 \
    background.padding_right=5 \
    icon.color=0xffffffff \
    icon.font="$FONT_FACE:Medium:14.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.color=0xffffffff \
    label.font="$FONT_FACE:Bold:12.0" \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5

sketchybar --add item current_space left \
    --set current_space \
    background.drawing=on \
    background.color=0xfff5a97f \
    background.height=26 \
    label.drawing=off \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

sketchybar --add item front_app left \
    --set front_app \
    background.drawing=on \
    background.color=0xffa6da95 \
    background.height=26 \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    icon= \
    icon.color=0xffa6da95 \
    icon.font="$FONT_FACE:Bold:23.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:16.0" \
    label.color=0xffcad3f5 \
    label.padding_left=5

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    background.drawing=on \
    background.color=0xffed8796 \
    background.height=26 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify right \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    label.drawing=off \
    label.padding_left=3 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
